export const langOptions = [
  { langCode: "auto", langName: "Auto Detect" },
  { langCode: "ab", langName: "Abkhaz" },
  { langCode: "ace", langName: "Acehnese" },
  { langCode: "ach", langName: "Acholi" },
  { langCode: "aa", langName: "Afar" },
  { langCode: "af", langName: "Afrikaans" },
  { langCode: "sq", langName: "Albanian" },
  { langCode: "alz", langName: "Alur" },
  { langCode: "am", langName: "Amharic" },
  { langCode: "ar", langName: "Arabic" },
  { langCode: "hy", langName: "Armenian" },
  { langCode: "as", langName: "Assamese" },
  { langCode: "av", langName: "Avar" },
  { langCode: "awa", langName: "Awadhi" },
  { langCode: "ay", langName: "Aymara" },
  { langCode: "az", langName: "Azerbaijani" },
  { langCode: "ban", langName: "Balinese" },
  { langCode: "bal", langName: "Baluchi" },
  { langCode: "bm", langName: "Bambara" },
  { langCode: "bci", langName: "Baoulé" },
  { langCode: "ba", langName: "Bashkir" },
  { langCode: "eu", langName: "Basque" },
  { langCode: "btx", langName: "Batak Karo" },
  { langCode: "bts", langName: "Batak Simalungun" },
  { langCode: "bbc", langName: "Batak Toba" },
  { langCode: "be", langName: "Belarusian" },
  { langCode: "bem", langName: "Bemba" },
  { langCode: "bn", langName: "Bengali" },
  { langCode: "bew", langName: "Betawi" },
  { langCode: "bho", langName: "Bhojpuri" },
  { langCode: "bik", langName: "Bikol" },
  { langCode: "bs", langName: "Bosnian" },
  { langCode: "br", langName: "Breton" },
  { langCode: "bg", langName: "Bulgarian" },
  { langCode: "bua", langName: "Buryat" },
  { langCode: "yue", langName: "Cantonese" },
  { langCode: "ca", langName: "Catalan" },
  { langCode: "ceb", langName: "Cebuano" },
  { langCode: "ch", langName: "Chamorro" },
  { langCode: "ce", langName: "Chechen" },
  { langCode: "ny", langName: "Chichewa" },
  { langCode: "zh-CN", langName: "Chinese (Simplified)" },
  { langCode: "zh-TW", langName: "Chinese (Traditional)" },
  { langCode: "chk", langName: "Chuukese" },
  { langCode: "cv", langName: "Chuvash" },
  { langCode: "co", langName: "Corsican" },
  { langCode: "crh", langName: "Crimean Tatar (Cyrillic)" },
  { langCode: "crh-Latn", langName: "Crimean Tatar (Latin)" },
  { langCode: "hr", langName: "Croatian" },
  { langCode: "cs", langName: "Czech" },
  { langCode: "da", langName: "Danish" },
  { langCode: "fa-AF", langName: "Dari" },
  { langCode: "dv", langName: "Dhivehi" },
  { langCode: "din", langName: "Dinka" },
  { langCode: "doi", langName: "Dogri" },
  { langCode: "dov", langName: "Dombe" },
  { langCode: "nl", langName: "Dutch" },
  { langCode: "dyu", langName: "Dyula" },
  { langCode: "dz", langName: "Dzongkha" },
  { langCode: "en", langName: "English" },
  { langCode: "eo", langName: "Esperanto" },
  { langCode: "et", langName: "Estonian" },
  { langCode: "ee", langName: "Ewe" },
  { langCode: "fo", langName: "Faroese" },
  { langCode: "fj", langName: "Fijian" },
  { langCode: "tl", langName: "Filipino" },
  { langCode: "fi", langName: "Finnish" },
  { langCode: "fon", langName: "Fon" },
  { langCode: "fr", langName: "French" },
  { langCode: "fr-CA", langName: "French (Canada)" },
  { langCode: "fy", langName: "Frisian" },
  { langCode: "fur", langName: "Friulian" },
  { langCode: "ff", langName: "Fulani" },
  { langCode: "gaa", langName: "Ga" },
  { langCode: "gl", langName: "Galician" },
  { langCode: "ka", langName: "Georgian" },
  { langCode: "de", langName: "German" },
  { langCode: "el", langName: "Greek" },
  { langCode: "gn", langName: "Guarani" },
  { langCode: "gu", langName: "Gujarati" },
  { langCode: "ht", langName: "Haitian Creole" },
  { langCode: "cnh", langName: "Hakha Chin" },
  { langCode: "ha", langName: "Hausa" },
  { langCode: "haw", langName: "Hawaiian" },
  { langCode: "iw", langName: "Hebrew" },
  { langCode: "hil", langName: "Hiligaynon" },
  { langCode: "hi", langName: "Hindi" },
  { langCode: "hmn", langName: "Hmong" },
  { langCode: "hu", langName: "Hungarian" },
  { langCode: "hrx", langName: "Hunsrik" },
  { langCode: "iba", langName: "Iban" },
  { langCode: "is", langName: "Icelandic" },
  { langCode: "ig", langName: "Igbo" },
  { langCode: "ilo", langName: "Ilocano" },
  { langCode: "id", langName: "Indonesian" },
  { langCode: "iu-Latn", langName: "Inuktut (Latin)" },
  { langCode: "iu", langName: "Inuktut (Syllabics)" },
  { langCode: "ga", langName: "Irish" },
  { langCode: "it", langName: "Italian" },
  { langCode: "jam", langName: "Jamaican Patois" },
  { langCode: "ja", langName: "Japanese" },
  { langCode: "jw", langName: "Javanese" },
  { langCode: "kac", langName: "Jingpo" },
  { langCode: "kl", langName: "Kalaallisut" },
  { langCode: "kn", langName: "Kannada" },
  { langCode: "kr", langName: "Kanuri" },
  { langCode: "pam", langName: "Kapampangan" },
  { langCode: "kk", langName: "Kazakh" },
  { langCode: "kha", langName: "Khasi" },
  { langCode: "km", langName: "Khmer" },
  { langCode: "cgg", langName: "Kiga" },
  { langCode: "kg", langName: "Kikongo" },
  { langCode: "rw", langName: "Kinyarwanda" },
  { langCode: "ktu", langName: "Kituba" },
  { langCode: "trp", langName: "Kokborok" },
  { langCode: "kv", langName: "Komi" },
  { langCode: "gom", langName: "Konkani" },
  { langCode: "ko", langName: "Korean" },
  { langCode: "kri", langName: "Krio" },
  { langCode: "ku", langName: "Kurdish (Kurmanji)" },
  { langCode: "ckb", langName: "Kurdish (Sorani)" },
  { langCode: "ky", langName: "Kyrgyz" },
  { langCode: "lo", langName: "Lao" },
  { langCode: "ltg", langName: "Latgalian" },
  { langCode: "la", langName: "Latin" },
  { langCode: "lv", langName: "Latvian" },
  { langCode: "lij", langName: "Ligurian" },
  { langCode: "li", langName: "Limburgish" },
  { langCode: "ln", langName: "Lingala" },
  { langCode: "lt", langName: "Lithuanian" },
  { langCode: "lmo", langName: "Lombard" },
  { langCode: "lg", langName: "Luganda" },
  { langCode: "luo", langName: "Luo" },
  { langCode: "lb", langName: "Luxembourgish" },
  { langCode: "mk", langName: "Macedonian" },
  { langCode: "mad", langName: "Madurese" },
  { langCode: "mai", langName: "Maithili" },
  { langCode: "mak", langName: "Makassar" },
  { langCode: "mg", langName: "Malagasy" },
  { langCode: "ms", langName: "Malay" },
  { langCode: "ms-Arab", langName: "Malay (Jawi)" },
  { langCode: "ml", langName: "Malayalam" },
  { langCode: "mt", langName: "Maltese" },
  { langCode: "mam", langName: "Mam" },
  { langCode: "gv", langName: "Manx" },
  { langCode: "mi", langName: "Maori" },
  { langCode: "mr", langName: "Marathi" },
  { langCode: "mh", langName: "Marshallese" },
  { langCode: "mwr", langName: "Marwadi" },
  { langCode: "mfe", langName: "Mauritian Creole" },
  { langCode: "chm", langName: "Meadow Mari" },
  { langCode: "mni-Mtei", langName: "Meiteilon (Manipuri)" },
  { langCode: "min", langName: "Minang" },
  { langCode: "lus", langName: "Mizo" },
  { langCode: "mn", langName: "Mongolian" },
  { langCode: "my", langName: "Myanmar (Burmese)" },
  { langCode: "nhe", langName: "Nahuatl (Eastern Huasteca)" },
  { langCode: "ndc-ZW", langName: "Ndau" },
  { langCode: "nr", langName: "Ndebele (South)" },
  { langCode: "new", langName: "Nepalbhasa (Newari)" },
  { langCode: "ne", langName: "Nepali" },
  { langCode: "bm-Nkoo", langName: "NKo" },
  { langCode: "no", langName: "Norwegian" },
  { langCode: "nus", langName: "Nuer" },
  { langCode: "oc", langName: "Occitan" },
  { langCode: "or", langName: "Odia (Oriya)" },
  { langCode: "om", langName: "Oromo" },
  { langCode: "os", langName: "Ossetian" },
  { langCode: "pag", langName: "Pangasinan" },
  { langCode: "pap", langName: "Papiamento" },
  { langCode: "ps", langName: "Pashto" },
  { langCode: "fa", langName: "Persian" },
  { langCode: "pl", langName: "Polish" },
  { langCode: "pt", langName: "Portuguese (Brazil)" },
  { langCode: "pt-PT", langName: "Portuguese (Portugal)" },
  { langCode: "pa", langName: "Punjabi (Gurmukhi)" },
  { langCode: "pa-Arab", langName: "Punjabi (Shahmukhi)" },
  { langCode: "qu", langName: "Quechua" },
  { langCode: "kek", langName: "Qʼeqchiʼ" },
  { langCode: "rom", langName: "Romani" },
  { langCode: "ro", langName: "Romanian" },
  { langCode: "rn", langName: "Rundi" },
  { langCode: "ru", langName: "Russian" },
  { langCode: "se", langName: "Sami (North)" },
  { langCode: "sm", langName: "Samoan" },
  { langCode: "sg", langName: "Sango" },
  { langCode: "sa", langName: "Sanskrit" },
  { langCode: "sat-Latn", langName: "Santali (Latin)" },
  { langCode: "sat", langName: "Santali (Ol Chiki)" },
  { langCode: "gd", langName: "Scots Gaelic" },
  { langCode: "nso", langName: "Sepedi" },
  { langCode: "sr", langName: "Serbian" },
  { langCode: "st", langName: "Sesotho" },
  { langCode: "crs", langName: "Seychellois Creole" },
  { langCode: "shn", langName: "Shan" },
  { langCode: "sn", langName: "Shona" },
  { langCode: "scn", langName: "Sicilian" },
  { langCode: "szl", langName: "Silesian" },
  { langCode: "sd", langName: "Sindhi" },
  { langCode: "si", langName: "Sinhala" },
  { langCode: "sk", langName: "Slovak" },
  { langCode: "sl", langName: "Slovenian" },
  { langCode: "so", langName: "Somali" },
  { langCode: "es", langName: "Spanish" },
  { langCode: "su", langName: "Sundanese" },
  { langCode: "sus", langName: "Susu" },
  { langCode: "sw", langName: "Swahili" },
  { langCode: "ss", langName: "Swati" },
  { langCode: "sv", langName: "Swedish" },
  { langCode: "ty", langName: "Tahitian" },
  { langCode: "tg", langName: "Tajik" },
  { langCode: "ber-Latn", langName: "Tamazight" },
  { langCode: "ber", langName: "Tamazight (Tifinagh)" },
  { langCode: "ta", langName: "Tamil" },
  { langCode: "tt", langName: "Tatar" },
  { langCode: "te", langName: "Telugu" },
  { langCode: "tet", langName: "Tetum" },
  { langCode: "th", langName: "Thai" },
  { langCode: "bo", langName: "Tibetan" },
  { langCode: "ti", langName: "Tigrinya" },
  { langCode: "tiv", langName: "Tiv" },
  { langCode: "tpi", langName: "Tok Pisin" },
  { langCode: "to", langName: "Tongan" },
  { langCode: "lua", langName: "Tshiluba" },
  { langCode: "ts", langName: "Tsonga" },
  { langCode: "tn", langName: "Tswana" },
  { langCode: "tcy", langName: "Tulu" },
  { langCode: "tum", langName: "Tumbuka" },
  { langCode: "tr", langName: "Turkish" },
  { langCode: "tk", langName: "Turkmen" },
  { langCode: "tyv", langName: "Tuvan" },
  { langCode: "ak", langName: "Twi" },
  { langCode: "udm", langName: "Udmurt" },
  { langCode: "uk", langName: "Ukrainian" },
  { langCode: "ur", langName: "Urdu" },
  { langCode: "ug", langName: "Uyghur" },
  { langCode: "uz", langName: "Uzbek" },
  { langCode: "ve", langName: "Venda" },
  { langCode: "vec", langName: "Venetian" },
  { langCode: "vi", langName: "Vietnamese" },
  { langCode: "war", langName: "Waray" },
  { langCode: "cy", langName: "Welsh" },
  { langCode: "wo", langName: "Wolof" },
  { langCode: "xh", langName: "Xhosa" },
  { langCode: "sah", langName: "Yakut" },
  { langCode: "yi", langName: "Yiddish" },
  { langCode: "yo", langName: "Yoruba" },
  { langCode: "yua", langName: "Yucatec Maya" },
  { langCode: "zap", langName: "Zapotec" },
  { langCode: "zu", langName: "Zulu" },
];
